/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "psqblpgqgnmppepierrn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzcWJscGdxZ25tcHBlcGllcnJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg2NzE3MTMsImV4cCI6MjEwNDI0NzcxM30.f15XMe3IXa0K-jyMJV9vc-5iweRqAL5JfbdVBpUZp-I"